{
    "name": "Stock Expiry Alert",
    "version": "18.0.1.0.2",
    "category": "Inventory",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 69,
    "currency": "EUR",
    "depends": ["stock", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/amadio_stock_expiry_alert_views.xml",
        "views/amadio_stock_expiry_alert_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Real-time lot/serial expiry monitoring with configurable alert lead times. Auto-email warnings before expiry. Enforces FEFO (First Expired First Out) on pick operations.",
    "description": "Real-time lot/serial expiry monitoring with configurable alert lead times. Auto-email warnings before expiry. Enforces FEFO (First Expired First Out) on pick operations.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
