{
    "name": "Vendor Performance Scorecard",
    "version": "18.0.1.0.2",
    "category": "Purchase",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 79,
    "currency": "EUR",
    "depends": ["purchase", "stock", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/amadio_vendor_performance_scorecard_views.xml",
        "views/amadio_vendor_performance_scorecard_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Rate vendors on delivery punctuality, quality, pricing accuracy, and service. Scorecards auto-update from PO receipts. Dashboard KPIs surface your best and worst performers.",
    "description": "Rate vendors on delivery punctuality, quality, pricing accuracy, and service. Scorecards auto-update from PO receipts. Dashboard KPIs surface your best and worst performers.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
