{
    "name": "Sales Commission Tracker",
    "version": "18.0.1.0.2",
    "category": "Sales",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 99,
    "currency": "EUR",
    "depends": ["sale", "account", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/amadio_sales_commission_tracker_views.xml",
        "views/amadio_sales_commission_tracker_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Configure commission rules by sales rep, team, product category, or customer. Auto-calculate commissions on paid invoices. Monthly commission statements with approval workflow.",
    "description": "Configure commission rules by sales rep, team, product category, or customer. Auto-calculate commissions on paid invoices. Monthly commission statements with approval workflow.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
