{
    "name": "Account Invoice Reminder",
    "version": "18.0.1.0.2",
    "category": "Accounting",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 59,
    "currency": "EUR",
    "depends": ["account", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/amadio_account_invoice_reminder_views.xml",
        "views/amadio_account_invoice_reminder_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Multi-stage dunning automation — configure reminder sequences (day 1, day 7, day 30 overdue) with escalating tone. Auto-send to customers, CC internal teams.",
    "description": "Multi-stage dunning automation — configure reminder sequences (day 1, day 7, day 30 overdue) with escalating tone. Auto-send to customers, CC internal teams.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
