{
    "name": "Inventory Reorder Optimizer",
    "version": "18.0.1.0.2",
    "category": "Inventory",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 79,
    "currency": "EUR",
    "depends": ["stock", "purchase"],
    "data": [
        "security/ir.model.access.csv",
        "views/amadio_inventory_reorder_optimizer_views.xml",
        "views/amadio_inventory_reorder_optimizer_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Analyzes 12 months of demand history to suggest optimal reorder points and safety stock levels. Flags slow-movers, predicts stockouts, and generates draft POs for approval.",
    "description": "Analyzes 12 months of demand history to suggest optimal reorder points and safety stock levels. Flags slow-movers, predicts stockouts, and generates draft POs for approval.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
