{
    "name": "Project Recurring Tasks",
    "version": "18.0.1.0.2",
    "category": "Project",
    "sequence": 1,
    "author": "AMADIO",
    "website": "https://amadio.io",
    "license": "OPL-1",
    "price": 49,
    "currency": "EUR",
    "depends": ["project", "mail"],
    "data": [
        "security/ir.model.access.csv",
        "views/amadio_project_recurring_tasks_views.xml",
        "views/amadio_project_recurring_tasks_menu.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "summary": "Define task templates with recurrence rules (daily/weekly/monthly/custom cron). Tasks auto-generate on schedule, pre-assigned, pre-tagged, and ready to work.",
    "description": "Define task templates with recurrence rules (daily/weekly/monthly/custom cron). Tasks auto-generate on schedule, pre-assigned, pre-tagged, and ready to work.",
    "images": ["static/description/banner.png", "static/description/icon.png"],
    "external_dependencies": {"python": [], "bin": []},
}
